// DappV3/src/app/components/campaigns/campaign-list-item/campaign-list-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { Web3Service } from 'src/app/services/web3.service';
import { CampaignService } from 'src/app/components/campaigns/campaign.service';
import { Campaign } from 'src/app/models/campaign';
import contractList from 'src/app/models/contract-list';
import {getDateFromEther, formatEtherDateToJs, formatDateToJsString} from 'src/app/utils/date';
import {formatPercent} from 'src/app/utils/numbers'
import {ethers, utils} from 'ethers';

@Component({
  selector: 'campaign-list-item',
  templateUrl: './campaign-list-item.component.html',
  styleUrls: ['./campaign-list-item.component.scss']
})
export class CampaignListItemComponent implements OnInit {

  @Input() campaignId: string='';
  @Input() campaignAddress: string='';
  @Input() currentChainId: string='';
  @Input() chainName: string = '';
  @Input() nativeCoin: {
    name: string;
    symbol: string;
    decimals: number;
  }| undefined = undefined;
  
  now = Date.now();
  campaign: Campaign;
  saleProgress: any;

  constructor(public web3Service: Web3Service,
    private campaignService: CampaignService) { }

  async ngOnInit() {
    this.campaign = await this.campaignService.getCampaignDetails(contractList[this.currentChainId].campaignList, this.campaignId!, this.nativeCoin!.decimals);

    const amount = parseFloat( this.campaign.totalCoinReceived ) ;
    const hardCap = parseFloat( this.campaign.hardCap );
    const softCap = parseFloat( this.campaign.softCap );

    this.saleProgress = 100 * Math.min( amount/softCap ,  amount/ hardCap)
    if(this.saleProgress==100){
      this.saleProgress = 100 * amount/ hardCap;
    }
  }

}


<div *ngIf="!campaign" class="card">
	<div class="card-body d-flex justify-content-center align-items-center">
		<img src="/assets/images/loader.gif" style="width:40px;height: 40px;"/>
	</div>
</div>

<div *ngIf="campaign" class="card" [routerLink]="['/campaigns', chainName, 'p', campaignId]">
	<div class="card-body">
		<div class="d-flex justify-content-left align-items-center">
			<c-avatar color="secondary" [status]="(campaign.status==2||campaign.status==3) ? 'danger':'success'" size="md">{{campaign.symbol}}</c-avatar>
			<div class="ms-2">
				{{campaign.name}} {{campaign.symbol}} 
			</div>

			<div *ngIf="campaign.saleStartTime.getTime() > now" class="ms-2">
                <div
                  class="countdown d-flex justify-content-center"
                  simpleCountdown
                  [dateTo]="campaign.saleStartTime.getTime()/1000"
                  [language]="'en'"
                  [endMessage]="'Ongoing Sale'"
                  [styles]="'
                    font-size: 16px;
                    color: red;
                    background-color: white;
                    padding: 8px 4px;
                    font-weight: bold;
                  '"
                  
                ></div>
                
            </div>
            <div *ngIf="campaign.saleEndTime.getTime() < now" class="ms-2">
                <div style="
                    font-size: 16px;
                    color: red;
                    background-color: white;
                    padding: 8px 4px;
                    font-weight: bold;
                  ">
                  	Sale Ended
              	</div>
                
            </div>
		</div>
		<div >
			<img [src]="campaign.logoUrl" [alt]="campaign.name+ ' Logo'" class="img-fluid" style="width:100px;"/>
		</div>

		<ul class="list-group mt-4 mx-0 ">
            <li class="list-group-item ">
                <div class="">
                	<div class="fw-bold">Soft Cap/Hard Cap</div>
                
                </div>
                <div >{{campaign.softCap}} {{nativeCoin.symbol}} to {{  campaign.hardCap}} {{nativeCoin.symbol}}</div>
            </li>
            <li class="list-group-item ">
	            <div class="">
	                <div class="fw-bold">Sale Rate</div>	                
	            </div>
	            <div >1 {{nativeCoin.symbol}} gets {{campaign.listRate}} {{campaign.symbol}}</div>
            </li>
            <li class="list-group-item">
                <div class="">
                <div class="fw-bold">DEX Listing Rate</div>
                
                </div>
                <div >1 {{nativeCoin.symbol}} gets {{campaign.dexListRate}} {{campaign.symbol}}</div>
            </li>

            <li class="list-group-item px-2 ">
                
                <p class="mb-2">{{campaign.description}}</p>

                <div>
                    <small>{{campaign.totalCoinReceived}} {{nativeCoin?.symbol??'Coin'}} /

                    {{ (campaign.totalCoinReceived >= campaign.softCap) ? (campaign.hardCap + ' ' + nativeCoin?.symbol  + ' Soft Cap Hit') : (campaign.softCap + ' '+ nativeCoin?.symbol ) }}
                    </small> 
                </div>
                
                <c-progress class="mb-3" [height]="20">
                  <c-progress-bar [value]="saleProgress"> 
                    {{campaign.totalCoinReceived}} {{nativeCoin?.symbol??'Coin'}}                            
                  </c-progress-bar>
                </c-progress>
            </li>


            
          </ul>
	</div>

	<div class="card-footer">
		<button type="button" class="btn btn-outline-primary">Share</button>
	</div>
</div>

// DappV2/src/content/campaigns/campaign-list-item.tsx
import { Helmet } from 'react-helmet-async';
// import PageHeader from './PageHeader';
import PageTitleWrapper from 'src/components/PageTitleWrapper';
import { Box, Grid,Avatar, Container,List,ListItem,  ListItemText,  ListItemIcon,  ListItemButton, TextField, Button } from '@mui/material';
import Card from '@mui/material/Card';
import CardHeader from '@mui/material/CardHeader';
import CardMedia from '@mui/material/CardMedia';
import CardContent from '@mui/material/CardContent';
import CardActions from '@mui/material/CardActions';
import Collapse from '@mui/material/Collapse';

import IconButton, { IconButtonProps } from '@mui/material/IconButton';
import Typography from '@mui/material/Typography';

import { red } from '@mui/material/colors';
import FavoriteIcon from '@mui/icons-material/Favorite';
import ShareIcon from '@mui/icons-material/Share';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import MoreVertIcon from '@mui/icons-material/MoreVert';

import Divider from '@mui/material/Divider';
import InboxIcon from '@mui/icons-material/Inbox';
import DraftsIcon from '@mui/icons-material/Drafts';
import Footer from 'src/components/Footer';
import { useParams } from "react-router-dom";
import { useContract, useNetwork, useSigner, useAccount } from 'wagmi';
import contractList from '../../constants/contract-list';
import CampaignListABI from '../../constants/campaign-list-abi.json';
import CampaignABI from '../../constants/campaign-abi.json';
import { useAsync } from "react-async";
import {useState, useEffect} from "react";
import {utils} from 'ethers';
import {useGetCampaign} from '../../hooks/useGetCampaign';

import Countdown from 'react-countdown';
import {Contract} from 'ethers';
import { getDateFromEther, formatEtherDateToJs } from '../../utils/date';
import LinearProgressBar from '../../components/LinearProgressBar';
import { useNavigate  } from "react-router-dom";

function formatPercent(value){
  if(!value) {
    return 0;
  }
  const val = utils.formatUnits(  value.toString(),0);
  const s = +val / 100 ;
  return s;
}

const CountDown_Ongoing = () => <span style={{"color": "#10df01"}}>Ongoing!</span>;

function CampaignListItem({campaignAddress, campaignId, signer, nativeCoin, chainId}) {
  
  const navigate = useNavigate ();
  // const classes = useStyles();

  const { value: campaignDetails, error: campaignGetError, loading: cLoading }  = useGetCampaign(contractList[chainId]?.campaignList??'0x0', campaignId, signer );
  
  const [isOpenForPayment, setIsOpenForPayment] = useState(false);

  const onCountdownCompleted = (e) => {
    setIsOpenForPayment(true);
  }

  
  useEffect(()=>{
    if(campaignDetails && getDateFromEther( campaignDetails.saleStartTime).getTime() < Date.now() && getDateFromEther( campaignDetails.saleEndTime).getTime() > Date.now() ){
      setIsOpenForPayment(true);
    }


  }, [campaignDetails])

  
  const navigateToHandler= () => {
      
      navigate(`/campaigns/${campaignId}`); 
  };

  return (
    <>

      {campaignDetails && <Card sx={[
          {
            '&:hover': {
              color: 'blue',
              backgroundColor: 'white',
              cursor: 'pointer'
            },
          },
          { maxWidth: 345 }
        ]}   onClick={navigateToHandler}>
          <CardHeader
            avatar={
              <Avatar sx={{ bgcolor: red[500] }} aria-label="recipe">
                {campaignDetails.symbol}
              </Avatar>
            }
            action={
              <IconButton aria-label="settings">
                <MoreVertIcon />
              </IconButton>
            }
            title={`${campaignDetails.name} (${campaignDetails.symbol})`}
            subheader={
              <>
                {(getDateFromEther( campaignDetails.saleEndTime).getTime() > Date.now()) && <div>
                  <Countdown onComplete={onCountdownCompleted} date={getDateFromEther( campaignDetails.saleStartTime).getTime()} >
                    <CountDown_Ongoing/>
                  </Countdown>
                </div>
                }

                {(getDateFromEther( campaignDetails.saleEndTime).getTime() < Date.now()) && <>
                  <div style={{"color": "#df1001"}}>Ended</div>
                </>
                }
              </>
              
                            
            }
          />
          <CardMedia
            component="img"
            height="194"
            image={campaignDetails.logoUrl}
            alt={`${campaignDetails.name} Logo`}
          />
          <CardContent>
            <List>
              
              <ListItem >
                <ListItemText primary="Soft Cap/Hard Cap" secondary={ `${ utils.formatUnits(  campaignDetails['softcap'].toString(),nativeCoin.decimals)} ${nativeCoin.symbol} to ${utils.formatUnits(  campaignDetails['hardcap'].toString(),nativeCoin.decimals)} ${nativeCoin.symbol}` }/>
              </ListItem>

              <ListItem >
                <ListItemText primary="Sale Rate" secondary={ `1 ${nativeCoin.symbol} gets ${campaignDetails['listRate']}` }/>
              </ListItem>

              <ListItem >
                <ListItemText primary="Dex Listing Rate" secondary={ `1 ${nativeCoin.symbol} gets ${campaignDetails['dexListRate']}` }/>
              </ListItem>
              
            </List>
            <Typography variant="body2" color="text.secondary">
              {campaignDetails.desc??''}
            </Typography>
            <Box sx={{ width: '100%' }}>
              <LinearProgressBar nativeCoinSymbol={nativeCoin.symbol} amount={ utils.formatUnits( campaignDetails.totalCoinReceived.toString(),nativeCoin.decimals) } softCap={utils.formatUnits(  campaignDetails['softcap'].toString(),nativeCoin.decimals)} hardCap={utils.formatUnits(  campaignDetails['hardcap'].toString(),nativeCoin.decimals)}/> 
            </Box>
            
          </CardContent>
          <CardActions disableSpacing>
            <IconButton aria-label="add to favorites">
              <FavoriteIcon />
            </IconButton>
            <IconButton aria-label="share">
              <ShareIcon />
            </IconButton>
            
          </CardActions>
          
        </Card>
      }
       
      
    </>
  );
}

export default CampaignListItem;
